title: Goost
tagline: Godot Engine Extension
description: >-
  A general-purpose, extensible and customizable C++ extension for Godot Engine.

logo_social: /assets/img/logo_social.png
github_username: goostengine
org_url: https://github.com/goostengine
repo: https://github.com/goostengine/goost

markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

defaults:
  - scope:
      path: ""
    values:
      layout: "default"

excerpt_separator: <!--more-->

sass:
  sass_dir: assets/css
  style: compressed

exclude: ["vendor", "Gemfile", "Gemfile.lock", "README.md", "LICENSE.txt"]
